name: Build crDroid ROM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/share/swift /usr/share/java /usr/share/sbt /usr/share/gradle /usr/share/ant /usr/share/maven /usr/local/lib/android /usr/local/share/boost /usr/local/share/powershell
          df -h

      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache libgl1-mesa-dev libxml2-utils xsltproc unzip python3 python3-pip
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          export PATH=~/bin:$PATH
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Initialize Repo
        run: |
          export PATH=~/bin:$PATH
          repo init -u https://github.com/crdroidandroid/android.git -b 11.0
          
      - name: Setup Local Manifests
        run: |
          mkdir -p .repo/local_manifests
          cat <<EOF > .repo/local_manifests/j2y18lte.xml
          <?xml version="1.0" encoding="UTF-8"?>
          <manifest>
            <project name="Gibiceli/android_device_samsung_j2y18lte" path="device/samsung/j2y18lte" remote="github" revision="main" />
            <project name="Gibiceli/android_vendor_samsung_j2y18lte" path="vendor/samsung/j2y18lte" remote="github" revision="main" />
          </manifest>
          EOF

      - name: Sync Repo
        run: |
          export PATH=~/bin:$PATH
          repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)

      - name: Build ROM
        run: |
          export PATH=~/bin:$PATH
          source build/envsetup.sh
          lunch crdroid_j2y18lte-userdebug
          mka bacon
